### ISSUE TITLE
больной

### ISSUE THREAD

**Issue by Woowz11** [wldoui/Early-Alpha-DxBIN-GUI#1]
в чём твоя проблема

**Comment by wldoui** [comment]
банан

**Comment by wldoui** [comment]
[больной](https://github.com/wldoui/Early-Alpha-DxBIN-GUI/issues/1#top)
#1
[Woowz11](https://github.com/Woowz11) opened this issue 2 days ago · 1 comment
ошибка

**Comment by wldoui** [comment]
исправил
